apiVersion: apps/v1
kind: Deployment
metadata:
  name: db
spec:
  replicas: 1
  selector:
    matchLabels:
      app: db
  template:
    metadata:
      labels:
        app: db
    spec:
      containers:
        - name: db
          image: {{ .Values.db.image }}
          env:
            - name: POSTGRES_USER
              value: {{ .Values.db.user }}
            - name: POSTGRES_PASSWORD
              value: {{ .Values.db.password }}
            - name: POSTGRES_DB
              value: {{ .Values.db.database }}
          ports:
            - containerPort: {{ .Values.db.port }}
---
apiVersion: v1
kind: Service
metadata:
  name: db
spec:
  selector:
    app: db
  ports:
    - port: {{ .Values.db.port }}
      targetPort: {{ .Values.db.port }}